#!/usr/bin/env bash
# Runs P1..P9 and assembles ~/agensea/PHASE0_FINDINGS.md.
# P1 and P2 are stop-the-world; every other probe failure is recorded and the
# run continues. All output passes through redact() in _lib.sh.
set -uo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
. "$HERE/_lib.sh"
FINDINGS="$ROOT/PHASE0_FINDINGS.md"
BLOCKERS="$OUT/blockers.txt"
rm -f "$OUT"/*.txt "$OUT"/*.ndjson 2>/dev/null
: > "$BLOCKERS"

{
  echo "# AgenSea Phase 0 - Environment Diagnostics"
  echo
  echo "Generated by \`apps/indexer/scripts/run_all.sh\`. Diagnostics only, no application code."
  echo "Secrets are masked throughout: first 30 characters, or half the value's length"
  echo "for values of 60 characters or fewer, so a short secret is never fully revealed."
  echo
  echo "| Fact | Value |"
  echo "|---|---|"
  echo "| RPC endpoint (masked) | \`$RPC_MASKED\` |"
  echo "| Historical source \`ALCHEMY_BSC\` (masked) | \`${ALCHEMY_MASKED:-<not set>}\` |"
  echo "| Foundry | $(cast --version 2>&1 | head -1) |"
  echo "| Node | $(node --version 2>&1) |"
  echo
} > "$FINDINGS"

run_probe() {
  local NAME="$1" SCRIPT="$2" STOP="${3:-no}"
  echo "==> $NAME ($SCRIPT)" >&2
  local TMP="$OUT/$NAME.section.md"
  if bash "$HERE/$SCRIPT" > "$TMP" 2>"$OUT/$NAME.stderr"; then
    :
  else
    # Prefer the probe's own conclusion line - probes report failures on stdout,
    # so an empty stderr says nothing useful.
    REASON="$(grep -m1 '^\*\*Conclusion:' "$TMP" 2>/dev/null | sed 's/\*\*Conclusion:\*\* //')"
    [ -z "$REASON" ] && REASON="$(tr '\n' ' ' < "$OUT/$NAME.stderr" | cut -c1-300)"
    [ -z "$REASON" ] && REASON="probe exited non-zero, no diagnostic emitted"
    echo "- **$NAME** - $REASON" >> "$BLOCKERS"
    if [ "$STOP" = "stop" ]; then
      cat "$TMP" >> "$FINDINGS"; echo >> "$FINDINGS"
      echo "STOP-THE-WORLD failure at $NAME" >&2
      return 1
    fi
  fi
  # P3's binary-search trace goes to stderr by design - fold it into the section.
  if [ "$NAME" = "P3" ] && [ -s "$OUT/$NAME.stderr" ]; then
    { echo; echo '<details><summary>binary search trace</summary>'; echo; echo '```'
      cat "$OUT/$NAME.stderr"; echo '```'; echo; echo '</details>'; } >> "$TMP"
  fi
  cat "$TMP" >> "$FINDINGS"; echo >> "$FINDINGS"
  return 0
}

run_probe P1 p1_chainid.sh          stop || exit 1
run_probe P2 p2_code.sh             stop || exit 1
run_probe P3 p3_archive_boundary.sh
run_probe P4 p4_blocktime.sh
run_probe P5 p5_getlogs_range.sh
run_probe P6 p6_historical_host.sh
run_probe P7 p7_data_reality.sh
run_probe P8 p8_registrations.sh
run_probe P9 p9_agenturi.sh

{
  echo "## Blockers"
  echo
  if [ -s "$BLOCKERS" ]; then cat "$BLOCKERS"; else echo "None - all nine probes completed without error."; fi
} >> "$FINDINGS"

# Final safety net: no live secret may survive in the findings file. An empty
# variable is skipped - grep -F "" matches every line and would fire falsely.
LEAK=0
for S in "$BSC_RPC" "$ALCHEMY_BSC" "$BSCSCAN_KEY"; do
  [ -z "$S" ] && continue
  if grep -qF "$S" "$FINDINGS"; then LEAK=1; fi
done
if [ "$LEAK" -eq 1 ]; then
  echo "FATAL: a secret leaked into $FINDINGS" >&2; exit 2
fi
echo "wrote $FINDINGS" >&2

# ---------------------------------------------------------------------------
# Acceptance checks. Each asserts a property the brief requires, against the
# artefacts actually produced. Printed to stdout so the run can be graded.
# ---------------------------------------------------------------------------
pass() { printf 'PASS  %s\n' "$1"; }
fail() { printf 'FAIL  %s\n' "$1"; ACC=1; }
ACC=0
echo
echo "=== ACCEPTANCE CHECKS ==="

# 1. The dead BscScan/Etherscan path must not be a primary path anywhere.
if grep -REl 'api\.bscscan\.com|api\.etherscan\.io' "$HERE" --include='*.sh' \
     | grep -q .; then
  if [ "$(grep -REl 'api\.bscscan\.com|api\.etherscan\.io' "$HERE" --include='*.sh')" = "$HERE/p6_historical_host.sh" ]; then
    pass "bscscan/etherscan appears only in p6_historical_host.sh (ruled-out record)"
  else
    fail "bscscan/etherscan host referenced outside the ruled-out record"
  fi
else
  fail "ruled-out record for bscscan/etherscan is missing"
fi

# 2. No probe may issue a request to a ruled-out host.
if grep -RE "curl[^|]*(api\.bscscan\.com|api\.etherscan\.io)" "$HERE" --include='*.sh' | grep -q .; then
  fail "a probe still sends a request to a ruled-out host"
else
  pass "no probe sends any request to a ruled-out host"
fi

# 3. 30-day span must be derived from P4's measurement, not a literal.
if [ -s "$OUT/p4_blocktime.txt" ] && [ -s "$OUT/p4_blocks30d.txt" ]; then
  AVG_A="$(cat "$OUT/p4_blocktime.txt")"; B30_A="$(cat "$OUT/p4_blocks30d.txt")"
  EXP="$(awk -v a="$AVG_A" 'BEGIN{printf "%.0f", 2592000/a}')"
  if [ "$EXP" = "$B30_A" ]; then
    pass "30d span $B30_A blocks == 2592000 / ${AVG_A}s measured (derived, not assumed)"
  else
    fail "30d span $B30_A does not match derivation from measured ${AVG_A}s (expected $EXP)"
  fi
else
  fail "P4 produced no measured block time, so no 30d span could be derived"
fi

# 4. Address normalisation: stored id/address files must contain no uppercase.
NORMBAD=0
for F in "$OUT/p7_agentids.txt" "$OUT/p7_clients.txt" "$OUT/p8_agentids.txt"; do
  [ -s "$F" ] || continue
  if LC_ALL=C grep -q '[A-Z]' "$F"; then echo "    uppercase found in $F"; NORMBAD=1; fi
done
[ "$NORMBAD" -eq 0 ] && pass "all stored ids/addresses are lowercase" \
                     || fail "uppercase survived into a stored id/address set"

# 5. P6 must report a max accepted range and a working-host verdict.
if [ -s "$OUT/p6_maxspan.txt" ] && [ -s "$OUT/p6_working_host.txt" ]; then
  pass "P6 recorded host=$(cat "$OUT/p6_working_host.txt") maxspan=$(cat "$OUT/p6_maxspan.txt") blocks"
else
  fail "P6 did not record a host verdict / max accepted range"
fi

# 6. The coverage window must follow the range P6 proved acceptable.
P6MAX="$(cat "$OUT/p6_maxspan.txt" 2>/dev/null || echo 0)"
P7SPAN="$(cat "$OUT/p7_span.txt" 2>/dev/null || echo 0)"
if [ "${P6MAX:-0}" -le 0 ]; then
  if [ "${P7SPAN:-0}" -eq 0 ]; then
    pass "no range accepted; coverage window is 0 and recorded as a blocker, not silently skipped"
  else
    fail "P6 accepted no range yet P7 claims a ${P7SPAN}-block window"
  fi
elif [ "${P7SPAN:-0}" -gt 0 ] && [ $(( P7SPAN % P6MAX )) -eq 0 ]; then
  pass "coverage window $P7SPAN blocks is an exact multiple of P6's accepted ${P6MAX}-block range"
else
  fail "coverage window $P7SPAN does not follow P6's accepted ${P6MAX}-block range"
fi

# 7. P8 must use exactly the window P7 used, or the ratio is not like-for-like.
if grep -q "COVERAGE WINDOW : ${P7SPAN} blocks" "$OUT/P8.section.md" 2>/dev/null; then
  pass "P8 window matches P7 window ($P7SPAN blocks) - ratio is like-for-like"
elif [ "${P7SPAN:-0}" -eq 0 ]; then
  pass "P8 correctly skipped - no window available from P7"
else
  fail "P8 window does not match P7's $P7SPAN blocks"
fi

# 8. No count field may render as two lines. `grep -c . f || echo 0` emits both
#    grep's 0 AND the fallback 0 on an empty file; the symptom is a stray
#    bare-numeric line inside a section's fenced block.
STRAY=0
for F in "$OUT/P7.section.md" "$OUT/P8.section.md"; do
  [ -s "$F" ] || continue
  if grep -qE '^[0-9]+$' "$F"; then
    echo "    stray bare-numeric line in $(basename "$F"): $(grep -nE '^[0-9]+$' "$F" | head -3 | tr '\n' ' ')"
    STRAY=1
  fi
done
[ "$STRAY" -eq 0 ] && pass "no split/duplicated count fields in P7/P8 output" \
                   || fail "a count field rendered as two lines (grep -c fallback bug)"

# 9. The chunk count must match the window exactly (no off-by-one).
if [ "${P6MAX:-0}" -gt 0 ] && [ "${P7SPAN:-0}" -gt 0 ]; then
  WANT=$(( P7SPAN / P6MAX ))
  GOT="$(grep -oE 'chunks=[0-9]+' "$OUT/P7.section.md" 2>/dev/null | head -1 | cut -d= -f2)"
  if [ "${GOT:-0}" = "$WANT" ]; then
    pass "chunk count $GOT == window $P7SPAN / range $P6MAX (no off-by-one)"
  else
    fail "chunk count ${GOT:-?} != expected $WANT for a $P7SPAN-block window at $P6MAX per chunk"
  fi
fi

echo
if [ "$ACC" -eq 0 ]; then echo "ACCEPTANCE: all checks passed"; else echo "ACCEPTANCE: one or more checks FAILED"; fi
